main:
  - name: Home
    url: /
    weight: 10
  - name: Posts
    url: /post/
    weight: 20
  - name: Projects
    url: /project/
    weight: 30
  - name: Publications
    url: /publication/
    weight: 40
  - name: Teaching
    url: /teaching/
    weight: 50
  - name: About
    url: /about/
    weight: 60
