description: "Academic CV and blog"
favicon:
  icon: "icon.png"

appearance:
  mode: auto
  color_scheme: ocean

locale:
  date_format: "Jan 2, 2006"

features:
  main_menu: true
  search: true
  comments:
    provider: ""
  analytics:
    google_analytics_id: ""
