name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      run: docker build --pull -t myimage .
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.148.2
        HUGO_EXTENDED: true
        TARGET_REPO: arinwongprommoon/arinwongprommoon.github.io
        TOKEN: ${{ secrets.GH_PAT }}
        HUGO_ARGS: --debug
        GO_VERSION: 1.25
